version: '3.4'

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "15672:15672"
    - "5672:5672"

  pessoasdataapi:
    image: ${DOCKER_REGISTRY-}pessoasdataapi
    build:
      context: .
      dockerfile: PessoasReadDataApi/Dockerfile
    environment:
      - APPLICATION_NAME="Pessoas Api"
      - DATABASE_HOST=localhost
      - DATABASE_NAME=master
      - DATABASE_USER=sa
      - DATABASE_PASS=123456
      - TIMEOUT=15
      - MAX_POOL_SIZE=250
      - TZ=America/Sao_Paulo
    ports:
      - "5342:80"

  