USE MASTER
GO

CREATE DATABASE [master]
GO
SELECT * FROM PESSOAS
USE [master]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[pessoas](
	[ID_PESSOA] [bigint] IDENTITY(1,1) NOT NULL,
	[PRIMEIRO_NOME] [string] NOT NULL,
	[SEGUNDO_NOME] [string] NOT NULL,
	[IDADE] [string] NOT NULL,
	[ENDERESSO] [string] NOT NULL,
	[TELEFONE] [string] NOT NULL,
	[EMAIL_VALIDACAO] [string] NOT NULL
 CONSTRAINT [ID_PESSOA] PRIMARY KEY CLUSTERED 
(
	[ID_PESSOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[pessoas] ADD  CONSTRAINT [DF_sensor_createdAt]  DEFAULT (getdate()) FOR [createdAt]
GO


